apiVersion: v1
kind: Service
metadata:
  name: locator-public
spec:
  ports:
  - port: 7070
    name: http
  type: NodePort
  selector:
    app: locator
---
apiVersion: v1
kind: Service
metadata:
  name: locator
spec:
  ports:
  - port: 10334
    name: locator
  clusterIP: None
  selector:
    app: locator
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: locator
spec:
  selector:
    matchLabels:
      app: locator
  serviceName: "locator"
  replicas: 2
  template:
    metadata:
      labels:
        app: locator
    spec:
      containers:
      - name: locator
        image: apachegeode/geode:1.4.0
        command:
        - sh
        - -c
        - |
          sh /geode-config/genenete-properties.sh locator && \
          gfsh start locator \
              --name=${HOSTNAME} \
              --dir=/data \
              --port=10334 \
              --properties-file=/root/geode.properties && \
          while true; do
            sleep 10
          done
        ports:
        - containerPort: 10334
          name: locator
        - containerPort: 1099
          name: jmx
        - containerPort: 7070
          name: http
        volumeMounts:
        - name: geode-config
          mountPath: /geode-config
        - name: geode-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              PID=$(cat /data/vf.gf.locator.pid) && [ -x /proc/${PID} ]
          initialDelaySeconds: 15
          periodSeconds: 1
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - |
                gfsh stop locator --dir=/data
      volumes:
      - name: geode-config
        configMap:
          name: geode-config
      - name: geode-data
        persistentVolumeClaim:
          claimName: geode-data
  volumeClaimTemplates:
  - metadata:
      name: geode-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi