apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  ports:
  - port: 40404
    name: server
  clusterIP: None
  selector:
    app: server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  serviceName: "server"
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: apachegeode/geode:1.6.0
        command:
        - sh
        - -c
        - |
          sh /geode-config/genenete-properties.sh server && \
          gfsh start server \
              --name=${HOSTNAME} \
              --dir=/data \
              --server-port=40404 \
              --properties-file=/root/geode.properties \
              --cache-xml-file=/server-config/cache.xml && \
          while true; do
            sleep 10
          done
        ports:
        - containerPort: 40404
          name: server
        - containerPort: 1099
          name: jmx
        volumeMounts:
        - name: geode-config
          mountPath: /geode-config
        - name: server-config
          mountPath: /server-config
        - name: geode-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              PID=$(cat /data/vf.gf.server.pid) && [ -x /proc/${PID} ]
          initialDelaySeconds: 20
          periodSeconds: 1
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - |
                gfsh stop locator --dir=/data
      initContainers:
      - name: wait-for-locator
        image: busybox
        command: 
          - sh
          - -c
          - |
            until nslookup locator; do 
              echo "Waiting for locator"
              sleep 2
            done;
      volumes:
      - name: geode-config
        configMap:
          name: geode-config
      - name: server-config
        configMap:
          name: server-config
      - name: geode-data
        persistentVolumeClaim:
          claimName: geode-data
  volumeClaimTemplates:
  - metadata:
      name: geode-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  cache.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <cache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://geode.apache.org/schema/cache" 
      xsi:schemaLocation="http://geode.apache.org/schema/cache http://geode.apache.org/schema/cache/cache-1.0.xsd" 
      version="1.0" lock-lease="120" lock-timeout="60" search-timeout="300" 
      is-server="true" copy-on-read="false">

        <region name="ExRegion1" refid="PARTITION_REDUNDANT_PERSISTENT" />
        <region name="ExRegion2" refid="PARTITION_REDUNDANT_PERSISTENT" />
    </cache>
    